---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: harvester-node-manager
  namespace: harvester-system
  labels:
    app.kubernetes.io/name: harvester-node-manager
    app.kubernetes.io/component: node-manager
    app.kubernetes.io/version: 0.1.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: harvester
      app.kubernetes.io/name: harvester-node-manager
  template:
    metadata:
      labels:
        name: harvester-node-manager
    spec:
      tolerations:
        # this toleration is to have the daemonset runnable on master nodes
        # remove it if your masters can't run pods
        - effect: NoSchedule
          key: node-role.kubernetes.io/master 
        - effect: NoExecute
          operator: Exists
      serviceAccountName: harvester-node-manager
      containers:
        - env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: HOST_PROC
              value: /host/proc
          name: node-manager
          image: rancher/harvester-node-manager:master-head
          imagePullPolicy: Always
          command:
            - harvester-node-manager
          securityContext:
            privileged: true
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          volumeMounts:
            - mountPath: /sys/kernel/mm
              name: mm
              readOnly: false
            - mountPath: /lib/modules
              name: modules
              readOnly: true
            - mountPath: /host/proc
              name: proc
              readOnly: true
            - mountPath: /var/run/dbus/system_bus_socket
              name: dbus-socket
              readOnly: true
            - mountPath: /host/etc/systemd
              name: host-systemd
            - mountPath: /host/oem
              name: host-oem
      volumes:
        - name: mm
          hostPath:
            path: /sys/kernel/mm
        - name: modules
          hostPath:
            path: /lib/modules
        - name: proc
          hostPath:
            path: /proc
        - name: dbus-socket
          hostPath:
            path: /var/run/dbus/system_bus_socket
            type: ""
        - name: host-systemd
          hostPath:
            path: /etc/systemd
            type: ""
        - name: host-oem
          hostPath:
            path: /oem
            type: ""
