---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: harvester-node-manager-webhook
  namespace: harvester-system
  labels:
    app.kubernetes.io/name: harvester-node-manager-webhook
    app.kubernetes.io/component: node-manager
    app.kubernetes.io/version: 0.1.0
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: harvester-node-manager-webhook
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: harvester-node-manager-webhook
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoExecute
          operator: Exists
      serviceAccountName: harvester-node-manager-webhook
      containers:
        - name: harvester-node-manager-webhook
          image: rancher/harvester-node-manager-webhook:master-head
          imagePullPolicy: Always
          ports:
          - containerPort: 8443
            name: https
            protocol: TCP
          env:
            - name: WEBHOOK_SERVER_HTTPS_PORT
              value: "8443"
            - name: NAMESPACE
              value: "harvester-system"

