---
apiVersion: v1
kind: Service
metadata:
  name: harvester-node-manager-webhook
  namespace: harvester-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: harvester-node-manager-webhook
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: 8443
