#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p bin
if [ "$(uname)" = "Linux" ]; then
    OTHER_LINKFLAGS="-extldflags -static -s"
fi

LINKFLAGS="-X github.com/harvester/node-manager/pkg/version.Version=$VERSION
           -X github.com/harvester/node-manager/pkg/version.GitCommit=$COMMIT $LINKFLAGS"

build() {
    local name="$1"
    local pkg="$2"

    CGO_ENABLED=0 go build -ldflags "$LINKFLAGS $OTHER_LINKFLAGS" -o "bin/$name" "$pkg"
    if [ "$CROSS" = "true" ] && [ "$ARCH" = "amd64" ]; then
        GOOS=darwin go build -ldflags "$LINKFLAGS" -o "bin/$name-darwin" "$pkg"
        GOOS=windows go build -ldflags "$LINKFLAGS" -o "bin/$name-windows" "$pkg"
    fi
}

build "harvester-node-manager" "."
