#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

IMAGE=${REPO}/harvester-node-manager:${TAG}
# https://ttl.sh/ is anonymous & ephemeral docker image registry
if [[ -n ${BUILD_FOR_CI} ]]; then
    IMAGE=ttl.sh/node-manager-${COMMIT}:1h
fi
DOCKERFILE=package/Dockerfile

buildx build --load \
    -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

if [[ -n ${BUILD_FOR_CI} ]]; then
    docker push ${IMAGE}
    echo ${IMAGE} pushed
fi
