#!/usr/bin/env bash

source $(dirname $0)/version

cd $(dirname $0)/..

IMAGE=${REPO}/harvester-node-manager-webhook:${TAG}
DOCKERFILE=package/Dockerfile.webhook

buildx build --load \
    -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
