#!/usr/bin/env bash

source $(dirname $0)/version

cd $(dirname $0)/..

mkdir -p dist/artifacts
cp bin/harvester-node-manager-webhook dist/artifacts/harvester-node-manager-webhook${SUFFIX}

IMAGE=${REPO}/harvester-node-manager-webhook:${TAG}
DOCKERFILE=package/Dockerfile.webhook
if [ -e ${DOCKERFILE}.${ARCH} ]; then
	DOCKERFILE=${DOCKERFILE}.${ARCH}
fi

docker build -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}
