#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

IMAGE=${REPO}/harvester-node-manager:${TAG}
# https://ttl.sh/ is anonymous & ephemeral docker image registry
if [[ -n ${BUILD_FOR_CI} ]]; then
    IMAGE=ttl.sh/node-manager-${COMMIT}:1h
fi
DOCKERFILE=package/Dockerfile

DOCKER_BUILD_EXTRA_ARGS=()
if [[ -n ${NO_CACHE} ]]; then
    DOCKER_BUILD_EXTRA_ARGS+=(--no-cache)
fi

docker build \
    "${DOCKER_BUILD_EXTRA_ARGS[@]}" \
    -f ${DOCKERFILE} -t ${IMAGE} .
echo Built ${IMAGE}

if [[ -n ${BUILD_FOR_CI} ]]; then
    docker push ${IMAGE}
    echo ${IMAGE} pushed
fi
