name: Pull Request Build

on:
  pull_request:

jobs:
  call-dapper-build:
    uses: ./.github/workflows/template-build.yml
    with:
      release-tag-name: pull-${{ github.event.number }}
      push: false
      skip-integration-tests: ${{ github.actor == 'renovate[bot]' }}
    secrets: inherit
